version: '3.6'

services:
  main:
    image: postgres:14
    ports: 
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./master:/var/lib/postgresql/data 
      - type: tmpfs
        target: /dev/shm
  replication_1:
    image: postgres:14
    ports: 
      - target: 5432
        published: 5434
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./replication:/var/lib/postgresql/data 
      - type: tmpfs
        target: /dev/shm